namespace: mdinicola
name: aws_tools_linux
version: 1.0.0
readme: README.md
authors:
- Mike Di Nicola <mike@mdinicola.com> (mdinicola.com)
description: Modules for installing AWS tools on Linux, such as the AWS CLI
license_file: 'COPYING'

tags: ['aws','aws_cli']

# dependencies: {}

repository: https://github.com/mdinicola/ansible-aws-tools-linux
documentation: https://github.com/mdinicola/ansible-aws-tools-linux
homepage: https://github.com/mdinicola/ansible-aws-tools-linux
issues: https://github.com/mdinicola/ansible-aws-tools-linux

build_ignore: []

# manifest: null

